builds:
  - binary: psenv
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=vendor

release:
  prerelease: auto

universal_binaries:
  - replace: true

brews:
  -
    name: pytoolbelt
    homepage: https://github.com/pytoolbelt/psenv
    tap:
      owner: pytoolbelt
      name: homebrew-awstools
    commit_author:
      name: Jesse Maitland
      email: jesse@pytoolbelt.com

checksum:
  name_template: 'checksums.txt'